<?php

/** @var Devils_HomeWidget_Block_Widget_Home $this */
$items = $this->getItems();
/** @var Devils_HomeWidget_Helper_Data $helper */
$helper = Mage::helper('devils_homewidget');

if (!empty($items)):
?>

<div class="homepage-banners row clearfix ">
    <?php
    $i = 1;
    foreach($items as $item):
        $width = (int) $item->getWidth();
        $height = (int) $item->getHeight();
        $imageUrl = $helper->getResizedImage($item->getImage(), $width, $height);
        $i++;
        if (!empty($imageUrl)):
        ?>
            <?php if ($i % 2):?></div><div class="homepage-banners row clearfix "><?php endif;?>
            <div class="grid_6">
                <a href="<?php echo $item->getLink(); ?>" target="_self">
                    <img src="<?php echo $imageUrl; ?>" alt="<?php echo $item->getName(); ?>" />
                </a>
            </div>
    <?php endif; endforeach; ?>
</div>

<?php endif; ?>
