<?php

/** @var Devils_HomeWidget_Block_Widget_Home $this */
$items = $this->getItems();
/** @var Devils_HomeWidget_Helper_Data $helper */
$helper = Mage::helper('devils_homewidget');

if (!empty($items)):
    ?>
    <div style="margin-bottom: 30px;">
        <?php
        $i = 0;
        foreach($items as $item):
        $id = (int) $item->getId();
        $width = (int) $item->getWidth();
        $height = (int) $item->getHeight();
        $resizeMode = $item->getResizeMode();
        $imageUrl = $helper->getResizedImage($item->getImage(), $width, $height, $resizeMode);
        $urlPath = trim($item->getUrlPath(), '/');
        $areas = $item->getAreas();
        $url = '';
        if ($urlPath && empty($areas)) {
            $url = $this->getUrl($urlPath);
        }
        $i++;
        if (!empty($imageUrl)):
        ?>
        <?php if ($i % 2): if ($i > 1) { echo '</div>'; } ?>
        <div class="homepage-banners row clearfix" style="margin:-13px 0 0!important;">
            <?php endif;?>
            <div class="grid_6">
                <?php if (empty($areas)):?>
                <?php echo ($url) ? '<a href="' . $url . '" target="_self">' : ''; ?>
                    <img src="<?php echo $imageUrl; ?>" alt="<?php echo $item->getName(); ?>" />
                <?php echo ($url) ? '</a>' : ''; ?>
                <?php else: ?>
                    <img src="<?php echo $imageUrl; ?>" alt="<?php echo $item->getName(); ?>"
                         usemap="homewidget_<?php echo $id;?>" />

                    <map name="homewidget_<?php echo $id;?>">
                    <?php foreach($areas as $area): ?>
                        <area shape="poly"
                              coords="<?php echo $area['points']; ?>"
                              href="<?php echo $this->getUrl(trim($area['url_path'], '/')); ?>"
                              title="<?php echo $area['name']; ?>"
                              alt="<?php echo $area['name']; ?>" />
                    <?php endforeach; ?>
                    </map>
                <?php endif; ?>
            </div>
            <?php endif; endforeach; ?>
        </div></div>

<?php endif; ?>
