<?php

/** @var Devils_HomeWidget_Block_Widget_Home $this */
$items = $this->getItems();
/** @var Devils_HomeWidget_Helper_Data $helper */
$helper = Mage::helper('devils_homewidget');

if (!empty($items)):
    ?>
    <div style="margin-bottom: 30px;">
        <?php
        $i = 0;
        foreach($items as $item):
        $width = (int) $item->getWidth();
        $height = (int) $item->getHeight();
        $resizeMode = $item->getResizeMode();
        $imageUrl = $helper->getResizedImage($item->getImage(), $width, $height, $resizeMode);
        $urlPath = trim($item->getUrlPath(), '/');
        $url = $this->getUrl($urlPath);
        $i++;
        if (!empty($imageUrl)):
        ?>
        <?php if ($i % 2): if ($i > 1) { echo '</div>'; } ?>
        <div class="homepage-banners row clearfix" style="margin:-13px 0 0!important;">
            <?php endif;?>
            <div class="grid_6">
                <a href="<?php echo $url; ?>" target="_self">
                    <img src="<?php echo $imageUrl; ?>" alt="<?php echo $item->getName(); ?>" />
                </a>
            </div>
            <?php endif; endforeach; ?>
        </div></div>

<?php endif; ?>
